apiVersion: v1
kind: Service
metadata:
  name: {{ include "torrent-store-chart.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "torrent-store-chart.name" . }}
    helm.sh/chart: {{ include "torrent-store-chart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 50051
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    app.kubernetes.io/name: {{ include "torrent-store-chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
