image:
  repository: ghcr.io/webtor-io/node-manager
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""
schedule: "*/5 * * * *"

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

rbac:
  create: true

contabo:
  clientId: ""
  clientSecret: ""
  apiUser: ""
  apiSecret: ""
