apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "web-ui.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "web-ui.name" . }}
    helm.sh/chart: {{ include "web-ui.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  {{- with .Values.config }}
  config.yaml: |
    {{- toYaml . | nindent 4 }}
  {{- end }}