apiVersion: v1
kind: Service
metadata:
  name: {{ include "jackett.fullname" . }}
  labels:
{{ include "jackett.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  internalTrafficPolicy: {{ .Values.service.internalTrafficPolicy }}
{{- if .Values.service.topologyKeys }}
  topologyKeys:
  {{- range .Values.service.topologyKeys }}
    - {{ . | quote }}
  {{- end }}
{{- end }}
  selector:
    app.kubernetes.io/name: {{ include "jackett.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
