apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rest-api.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "rest-api.name" . }}
    helm.sh/chart: {{ include "rest-api.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "rest-api.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "rest-api.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PROM_ADDR
              value: "{{ .Values.prometheus.address }}"
            - name: NODE_IFACE
              value: "{{ .Values.node.network.iface }}"
            - name: NODE_LABEL_PREFIX
              value: "{{ .Values.node.label.prefix }}"
            - name: EXPORT_SSL
              value: "{{ .Values.export.ssl }}"
            - name: EXPORT_DOMAIN
              value: "{{ .Values.export.domain }}"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: httpprobe
              containerPort: 8081
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /liveness
              port: httpprobe
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /readiness
              port: httpprobe
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
