replicaCount: 1

image:
  repository: ghcr.io/webtor-io/abuse-store
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

postgres:
  instances: 2
  name: abusestore
  volume:
    size: "10Gi"
  nodeAffinity: {}
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 500m
      memory: 512Mi

mailgun:
  key: ""
  domain: webtor.io
  apiBase: https://api.eu.mailgun.net/v3

mail:
  sender: noreply@webtor.io
  support: support@webtor.io
