replicaCount: 1

image:
  repository: ghcr.io/webtor-io/dnslb
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

rbac:
  create: true

cloudflare:
  apiKey: ""
  apiEmail: ""

log:
  verbose: false
  json: true

node:
  selector: ""
  addressType: ExternalIP

pod:
  selector: "app.kubernetes.io/component=controller,app=nginx-ingress"
  namespace: ""

ingress:
  namespace: ""

interval:
  check: 10
  fullCheck: 600

concurrency: 5
