apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "torrent-http-proxy.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "torrent-http-proxy.name" . }}
    helm.sh/chart: {{ include "torrent-http-proxy.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  {{- with .Values.clients }}
  clients.yaml: |
    {{- toYaml . | nindent 4 }}
  {{- end }}