replicaCount: 1

image:
  repository: ghcr.io/webtor-io/content-prober
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}