image:
  repository: ghcr.io/webtor-io/download-progress
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  ports: 
    http: 80
    grpc: 50051
  internalTrafficPolicy: Cluster
  topologyKeys: []

update:
  maxUnavailable: 1

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}