replicaCount: 1

image:
  repository: ghcr.io/webtor-io/web-ui
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""
secret: ""
domain: ""

config: {}

service:
  type: ClusterIP
  port: 80
  internalTrafficPolicy: Cluster
  topologyKeys: []

ingress:
  enabled: false
  annotations: {}
  paths: ['/']
  hosts: []
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
