replicaCount: 1

image:
  repository: ghcr.io/webtor-io/blog
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations: {}
  paths: ['/']
  hosts: []
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
