apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "abuse-store.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "abuse-store.name" . }}
    helm.sh/chart: {{ include "abuse-store.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "abuse-store.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "abuse-store.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PG_DATABASE
              value: "{{ .Values.postgres.name }}"
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.postgres.name }}.acid-{{ include "abuse-store.fullname" . }}.credentials.postgresql.acid.zalan.do"
                  key: password
            - name: PG_USER
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.postgres.name }}.acid-{{ include "abuse-store.fullname" . }}.credentials.postgresql.acid.zalan.do"
                  key: username
            - name: PG_HOST
              value: "acid-{{ include "abuse-store.fullname" . }}-pooler"
            - name: PG_PORT
              value: "5432"
            - name: PG_SSL
              value: "true"
            - name: MAILGUN_KEY
              value: {{ .Values.mailgun.key }}
            - name: MAILGUN_DOMAIN
              value: {{ .Values.mailgun.domain }}
            - name: MAILGUN_API_BASE
              value: {{ .Values.mailgun.apiBase }}
            - name: MAIL_SENDER
              value: {{ .Values.mail.sender }}
            - name: MAIL_SUPPORT
              value: {{ .Values.mail.support }}
          ports:
            - name: grpc
              containerPort: 50051
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: grpc
          readinessProbe:
            tcpSocket:
              port: grpc
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
