apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx-vod.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "nginx-vod.name" . }}
    helm.sh/chart: {{ include "nginx-vod.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.http }}
      targetPort: http
      protocol: TCP
      name: http
  internalTrafficPolicy: {{ .Values.service.internalTrafficPolicy }}
{{- if .Values.service.topologyKeys }}
  topologyKeys:
  {{- range .Values.service.topologyKeys }}
    - {{ . | quote }}
  {{- end }}
{{- end }}
  selector:
    app.kubernetes.io/name: {{ include "nginx-vod.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
