apiVersion: batch/v1
kind: CronJob
metadata:
  name: "{{ include "abuse-fetcher.fullname" . }}"
  labels:
    app.kubernetes.io/name: {{ include "abuse-fetcher.name" . }}
    helm.sh/chart: {{ include "abuse-fetcher.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  schedule: "{{ .Values.schedule }}"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 10
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: "{{ .Chart.Name }}"
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
          restartPolicy: Never
        {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
        {{- end }}
      backoffLimit: 0
