# Default values for abuse-fetcher.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: webtor/abuse-fetcher
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""
schedule: "*/30 * * * *"

rbac:
  create: true

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
