image:
  repository: ghcr.io/webtor-io/node-dns-syncer
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""
schedule: "*/5 * * * *"

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

rbac:
  create: true

cloudflare:
  apiKey: ""
  email: ""
  zones: ""

domainName:
  prefix: "abra--"
  suffix: "."

nodes:
  labelSelector: ""
  labelName: ""
  addressType: "ExternalIP"
