apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rapidapi-gateway.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "rapidapi-gateway.name" . }}
    helm.sh/chart: {{ include "rapidapi-gateway.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "rapidapi-gateway.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "rapidapi-gateway.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: BASIC_RATE
              value: "{{ .Values.features.basic.rate }}"
            - name: BASIC_CONNECTIONS
              value: "{{ .Values.features.basic.connections }}"
            - name: PRO_RATE
              value: "{{ .Values.features.pro.rate }}"
            - name: PRO_CONNECTIONS
              value: "{{ .Values.features.pro.connections }}"
            - name: ULTRA_RATE
              value: "{{ .Values.features.ultra.rate }}"
            - name: ULTRA_CONNECTIONS
              value: "{{ .Values.features.ultra.connections }}"
            - name: MEGA_RATE
              value: "{{ .Values.features.mega.rate }}"
            - name: MEGA_CONNECTIONS
              value: "{{ .Values.features.mega.connections }}"
            - name: WEBTOR_API_KEY
              value: "{{ .Values.webtor.api.key }}"
            - name: WEBTOR_API_SECRET
              value: "{{ .Values.webtor.api.secret }}"
            - name: RAPID_API_PROXY_SECRET
              value: "{{ .Values.rapidApi.proxy.secret }}"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: httpprobe
              containerPort: 8081
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /liveness
              port: httpprobe
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /readiness
              port: httpprobe
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
